name: demo firs party action
description: Greet someone and generate a random number as an output

inputs:
  who-to-greet:
    description: just giv some value man ;)
    required: true
    #if reuqired why default?
    default: world

outputs:
  random-number:
    description: some random random
    value: ${{ steps.generate-random.outputs.random-number }} 
runs:
  using: 'composite'
  steps:
    - name: Greet
      run: echo "hello, $who_to_greet"
      shell: bash
      env:
        who_to_greet: ${{ inputs.who-to-greet }}
    - name: generate a random
      id: generate-random
      run: echo "random-number=$RANDOM" >> $GITHUB_OUTPUT
      shell: bash