name: passing data
on:
  workflow_dispatch:

jobs:
  producer:
    runs-on: ubuntu-24.04
    outputs:
      foo: ${{ steps.generate-foo.outputs.foo }}
    steps:
      - name: generate and export foo
        id: generate-foo
        run: |
          foo=bar
          echo "foo=${foo}" >> "$GITHUB_OUTPUT"
          echo "FOO=${foo}" >> "$GITHUB_ENV"
      - name: inspect values inside producer
        run: |
          echo "foo (set via github output):    ${{ steps.generate-foo.outputs.foo}}"
          echo "FOO (set via github env):       $FOO"

  consumer:
    runs-on: ubuntu-24.04
    needs: producer
    steps:
      - name: inspect producer outputs
        run: |
          echo "foo (via github output):  ${{ needs.producer.outputs.foo }}" 
          echo "FOO (via github env):     ${FOO:-<UNSET>}"