name: secrets and environments
on:
  workflow_dispatch:

env:
  EXAMPLE_REPOSITORY_SECRET: ${{ secrets.EXAMPLE_REPOSITORY_SECRET }}
  EXAMPLE_REPOSITORY_VARIABLE: ${{ vars.EXAMPLE_REPOSITORY_VARIABLE }}

jobs:
  staging-environment:
    runs-on: ubuntu-24.04
    steps:
      - run: |
        echo "repo secret (masked): $EXAMPLE_REPOSITORY_SECRET"
        echo "repo var:             $EXAMPLE_REPOSITORY_VARIABLE" 