name: secrets and environments
on:
  workflow_dispatch:

env:
  EXAMPLE_REPOSITORY_SECRET: ${{ secrets.EXAMPLE_REPOSITORY_SECRET }}
  EXAMPLE_REPOSITORY_VARIABLE: ${{ vars.EXAMPLE_REPOSITORY_VARIABLE }}

jobs:
  global-environment:
    runs-on: ubuntu-24.04
    steps:
      - run: |
          echo "global runner (no env defined)"
          echo "repo secret (masked): $EXAMPLE_REPOSITORY_SECRET"
          echo "repo var:             $EXAMPLE_REPOSITORY_VARIABLE" 
  staging-environment:
    runs-on: ubuntu:24.04
    environment: staging
    env:
      EXAMPLE_ENVIRONMENT_SECRET: ${{ secrets.EXAMPLE_ENVIRONMENT_SECRET}}
      EXAMPLE_ENVIRONMENT_VARIABLE: ${{ vars.EXAMPLE_ENVIRONMENT_VARIABLE}}

    steps:
      - name: inspect vars and secrets in staging environment
        run: |
          echo "staging runner (staging env )"
          echo "repo secret (masked): $EXAMPLE_REPOSITORY_SECRET"
          echo "repo var:             $EXAMPLE_REPOSITORY_VARIABLE" 
          echo "env secret (masked):  $EXAMPLE_ENVIRONMENT_SECRET"
          echo "env var:              $EXAMPLE_ENVIRONMENT_VARIABLE" 
   production-environment:
    runs-on: ubuntu:24.04
    environment: production
    env:
      EXAMPLE_ENVIRONMENT_SECRET: ${{ secrets.EXAMPLE_ENVIRONMENT_SECRET}}
      EXAMPLE_ENVIRONMENT_VARIABLE: ${{ vars.EXAMPLE_ENVIRONMENT_VARIABLE}}

    steps:
      - name: inspect vars and secrets in staging environment
        run: |
          echo "staging runner (staging env )"
          echo "repo secret (masked): $EXAMPLE_REPOSITORY_SECRET"
          echo "repo var:             $EXAMPLE_REPOSITORY_VARIABLE" 
          echo "env secret (masked):  $EXAMPLE_ENVIRONMENT_SECRET"
          echo "env var:              $EXAMPLE_ENVIRONMENT_VARIABLE" 
 