name: Step Types

on:
  workflow_dispatch:

jobs:
  say-hello-inline-bash:
    runs-on: ubuntu-24.04
    steps:
      - run: "echo Hello from an inlin ebash script in a Github Action Workflow!"

  say-hello-inline-python:
    runs-on: ubuntu-24.04
    steps:
      - run: print("Hello from an inline python script in a Github Action Workfflow!")
        shell: python
  say-hello-action:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/hello-world-javascript-action@79ac0da13ee392da3fdd151813d5ce4658cb7e27
        with:
          who-to-greet: "from an action in the Githuv Action marketplace!"